set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

set(TOOLCHAIN_DIR   /opt/rtk-toolchain/asdk-10.3.1)
set(SDK_TOOLCHAIN  ${TOOLCHAIN_DIR}/linux/newlib)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOL_PREFIX arm-none-eabi-)
set(CMAKE_C_COMPILER    ${SDK_TOOLCHAIN}/bin/${TOOL_PREFIX}gcc)
set(CMAKE_CXX_COMPILER  ${SDK_TOOLCHAIN}/bin/${TOOL_PREFIX}g++)
set(CMAKE_RANLIB        ${SDK_TOOLCHAIN}/bin/${TOOL_PREFIX}ranlib)
set(CMAKE_AR            ${SDK_TOOLCHAIN}/bin/${TOOL_PREFIX}ar)

set(ARCH_FLAGS          "-O2 -mcpu=cortex-a32 -mfpu=neon -mfloat-abi=hard -marm")
set(CMAKE_C_FLAGS       "${ARCH_FLAGS}" CACHE STRING "" FORCE )
set(CMAKE_CXX_FLAGS     "${ARCH_FLAGS}" CACHE STRING "" FORCE )
set(CMAKE_ASM_FLAGS     ${CMAKE_C_FLAGS} CACHE STRING "" FORCE )
set(CMAKE_LD_FLAGS      ${CMAKE_C_FLAGS} CACHE STRING "" FORCE )

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )

set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qcD <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> -D <TARGET>")
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcD <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> -D <TARGET>")
